### ISSUE TITLE
adding readonly input fields to the input_spec

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra-fsl#49]
- allowing to add a completely new input fields as a part of `inputs_metadata`. This can be useful when complicated `xor` structure is required by the tool. Example would be `fslroi` that has three different option:

```
fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize>
fslroi <input> <output> <tmin> <tsize>
fslroi <input> <output> <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize>
```

Nipype has some `xor` structure that doesn't fully cover all usecases, see [here](https://github.com/nipy/nipype/blob/450be34b4540a0c3c6761cc04cc9132fdac5f5c8/nipype/interfaces/fsl/utils.py#L416).

In pydra we could probably handle this by adding `readonly` arguments like this:

```
  inputs_metadata:
    x-z_range:
      readonly: True
      argstr: "{x_min} {x_size} {y_min} {y_size} {z_min} {z_size}"
      requires: [x_min, x_size, y_min, y_size, z_min, z_size]
      position: 2

    t_range:
      readonly: True
      argstr: "{t_min} {t_size}"
      requires: [t_min, t_size]
      position: 3
```
